### ISSUE TITLE
Support stretchr/testify/suite.Suite helpers

### ISSUE THREAD

**Issue by Antonboom** [kulti/thelper#29]
Hello!

Thank u for linter.

Example of that I mean:
```go
import "github.com/stretchr/testify/suite"

type ServiceSuite struct {
    suite.Suite
    // ...
}

func (s *ServiceSuite) TestGetUser() {
    // ...
    s.requireMakeRequest()
}

func (s *ServiceSuite) requireMakeRequest() {  // Private method with suite API calls is helper.
    s.T().Helper()
    
    // Do stuff ...
    s.Equal(http.StatusOk, resp.StatusCode)
}
```

**Comment by kulti** [comment]
Hi!

Thank you for your idea. I've thought about that a long time ago, but was not sure that this linter should support all suite frameworks.

Maybe, this functionality should be implemented inside another linter specific for testify libs? I think, another great suggestion can be made, like "don't use Equal for float" or "use NoError instead of Nil for error check". What do you think?

**Comment by Antonboom** [comment]
Yes, I also have a couple of ideas on this subject, for example, they often do
```go
require.Error(t, err, io.EOF) // ErrorIs was expected.
```

Looks like it's really worth making `testifylint` )) All the more so for 2020 this library ranks [first place](https://blog.jetbrains.com/go/2021/02/03/the-state-of-go/).
